"""change collums delete

Revision ID: 0ed94fa1da13
Revises: 991106afdfa7
Create Date: 2025-05-28 03:10:50.910499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ed94fa1da13'
down_revision: Union[str, None] = '991106afdfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='whatsapp_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='whatsapp_chat')
    # ### end Alembic commands ###
