"""create collumns for whatsapp message

Revision ID: 51c6083fb3da
Revises: c24be8a18ce5
Create Date: 2025-05-23 01:20:02.805853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c6083fb3da'
down_revision: Union[str, None] = 'c24be8a18ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_chat_messages', sa.Column('message_type', sa.String(length=15), nullable=False), schema='whatsapp_chat')
    op.add_column('whatsapp_chat_messages', sa.Column('message_id', sa.String(length=300), nullable=False), schema='whatsapp_chat')
    op.add_column('whatsapp_chat_messages', sa.Column('sent', sa.Boolean(), nullable=False), schema='whatsapp_chat')
    op.add_column('whatsapp_chat_messages', sa.Column('delivered', sa.Boolean(), nullable=False), schema='whatsapp_chat')
    op.add_column('whatsapp_chat_messages', sa.Column('read', sa.Boolean(), nullable=False), schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=False,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'message',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=8000),
               existing_nullable=False,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False,
               schema='whatsapp_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'message',
               existing_type=sa.String(length=8000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False,
               schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'read', schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'delivered', schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'sent', schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'message_id', schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'message_type', schema='whatsapp_chat')
    # ### end Alembic commands ###
