"""add more collumns

Revision ID: c24be8a18ce5
Revises: abb71c87384d
Create Date: 2025-05-20 22:56:13.555704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c24be8a18ce5'
down_revision: Union[str, None] = 'abb71c87384d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_chat_messages', sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='whatsapp_chat')
    op.alter_column('whatsapp_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='whatsapp_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='whatsapp_chat')
    op.drop_column('whatsapp_chat_messages', 'deleted_at', schema='whatsapp_chat')
    # ### end Alembic commands ###
