"""change

Revision ID: c57902db3dc3
Revises: 51c6083fb3da
Create Date: 2025-05-24 04:42:13.798953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57902db3dc3'
down_revision: Union[str, None] = '51c6083fb3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'message_id',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=False,
               schema='whatsapp_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_chat_messages', 'message_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False,
               schema='whatsapp_chat')
    # ### end Alembic commands ###
